### ISSUE TITLE
admin ozellikleri

### ISSUE THREAD

**Issue by buseozkan** [CyprusCodes/cypruscodes#10]

**Comment by kirakoki** [comment]
Bu issue , bu repoynan alakali deil. 

Please recreate and link it to cypruscodes/teaching-platform-fe

**Comment by buseozkan** [comment]
oki tokii

**Comment by kirakoki** [comment]
Can we please link a PR to this ?

**Comment by buseozkan** [comment]
This has been resolved as manage blogs however manage blogs by admin doesn't show the publishing list @kirakoki

**Comment by kirakoki** [comment]
this is fixed now
